#!/usr/bin/env python3
"""
Apply a macOS Big Sur–style rounded squircle mask to a square PNG so the
resulting .icns (generated by `tauri icon`) shows with proper rounded
corners in Finder, Dock, and Launchpad.

Background
----------
macOS no longer auto-rounds .icns artwork: whatever shape you ship is what
the OS displays. Apple's icon template uses a ~824 px artwork area inside
a 1024 px transparent canvas, with the artwork itself masked by a
continuous "squircle". A rounded rectangle with radius ≈ 185 px is a
faithful approximation that's indistinguishable from the real squircle for
all practical purposes.

Usage
-----
    python3 scripts/round-icon.py path/to/source.png
    # → writes path/to/source.rounded.png next to it

    python3 scripts/round-icon.py path/to/source.png path/to/out.png
    # → writes to the explicit destination

Then regenerate every Tauri icon size and rebuild:

    npm run tauri icon path/to/source.rounded.png
    (cd src-tauri && cargo clean)
    npm run tauri build

Dependencies
------------
Requires Pillow:
    python3 -m pip install --break-system-packages Pillow
or inside a virtualenv:
    python3 -m venv .venv && source .venv/bin/activate
    pip install Pillow
"""

import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw
except ImportError:
    print(
        "This script needs Pillow. Install with:\n"
        "  python3 -m pip install --break-system-packages Pillow",
        file=sys.stderr,
    )
    sys.exit(1)


# Apple's macOS Big Sur+ icon spec (rounded to the closest squircle approx):
#   - Canvas size: 1024 x 1024 (transparent margin around the shape)
#   - Artwork area: 824 x 824, centered (100 px padding on each side)
#   - Corner radius: 185 px on the 824 box (matches the system squircle
#     within a pixel or two; the eye can't tell the difference)
CANVAS = 1024
ARTWORK = 824
PADDING = (CANVAS - ARTWORK) // 2
CORNER_RADIUS = 185


def apply_squircle(src_path: Path, dst_path: Path) -> None:
    src = Image.open(src_path).convert("RGBA")

    # Scale source down (or up) to fit the inner artwork area exactly.
    # LANCZOS gives the best quality for both directions.
    src = src.resize((ARTWORK, ARTWORK), Image.LANCZOS)

    # Build a grayscale rounded-rect mask. White (255) = visible, 0 = clipped.
    mask = Image.new("L", (ARTWORK, ARTWORK), 0)
    draw = ImageDraw.Draw(mask)
    draw.rounded_rectangle(
        [(0, 0), (ARTWORK - 1, ARTWORK - 1)],
        radius=CORNER_RADIUS,
        fill=255,
    )

    # Apply the mask as alpha so the source is clipped to the shape.
    shaped = Image.new("RGBA", (ARTWORK, ARTWORK), (0, 0, 0, 0))
    shaped.paste(src, (0, 0), mask)

    # Place the shaped artwork on a 1024×1024 transparent canvas with the
    # standard padding around it.
    canvas = Image.new("RGBA", (CANVAS, CANVAS), (0, 0, 0, 0))
    canvas.paste(shaped, (PADDING, PADDING), shaped)

    canvas.save(dst_path, "PNG", optimize=True)
    print(f"Wrote {dst_path} ({CANVAS}×{CANVAS}, rounded squircle)")


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 1

    src = Path(sys.argv[1]).expanduser().resolve()
    if not src.exists():
        print(f"Source not found: {src}", file=sys.stderr)
        return 1

    if len(sys.argv) >= 3:
        dst = Path(sys.argv[2]).expanduser().resolve()
    else:
        dst = src.with_suffix("").with_name(src.stem + ".rounded.png")

    apply_squircle(src, dst)
    return 0


if __name__ == "__main__":
    sys.exit(main())
